[dataloaders]
[dataloaders.train]
[dataloaders.train.dataset]
data_path = "/home/khaymonenko/aste/data/bank_3200/train_full.txt"
datareader_class_name = "SentenceBankDataReader"
dataset_class_name = "SimpleDiscriminativeDataset"

tokenizer_class_name = "AutoTokenizer"
tokenizer_model_name = "ai-forever/ruRoberta-large"

max_length = 512

[dataloaders.train.dataloader]
batch_size = 8
num_workers = 8

[dataloaders.dev.dataset]
data_path = "/home/khaymonenko/aste/data/bank_3200/dev_full.txt"
datareader_class_name = "SentenceBankDataReader"
dataset_class_name = "SimpleDiscriminativeDataset"

tokenizer_class_name = "AutoTokenizer"
tokenizer_model_name = "ai-forever/ruRoberta-large"

max_length = 512

[dataloaders.dev.dataloader]
batch_size = 32
num_workers = 8

[dataloaders.test.dataset]
data_path = "/home/khaymonenko/aste/data/bank_3200/test_full.txt"
datareader_class_name = "SentenceBankDataReader"
dataset_class_name = "SimpleDiscriminativeDataset"

tokenizer_class_name = "AutoTokenizer"
tokenizer_model_name = "ai-forever/ruRoberta-large"

max_length = 512

[dataloaders.test.dataloader]
batch_size = 32
num_workers = 8

[train]
tokenizer_class_name = "AutoTokenizer"
model_class_name = "AutoModel"
model_name = "ai-forever/ruRoberta-large"

aste_model_class_name = "BaseDiscriminatorModel"

freeze = 0

epochs = 20
