train_path = "/home/khaymonenko/aste/data/bank_3200/train_full.txt"
dev_path = "/home/khaymonenko/aste/data/bank_3200/dev_full.txt"
test_path = "/home/khaymonenko/aste/data/bank_3200/test_full.txt"

model_name = "ai-forever/FRED-T5-1.7B"

model_class_name = "T5ForConditionalGeneration"
tokenizer_class_name = "GPT2Tokenizer"

input_max_length = 512
output_max_length = 100

train_batch_size = 8
dev_batch_size = 2

freeze = 400

num_workers = 4
epochs = 20
